name: goreleaser

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17.x        
      -
        name: Run GoReleaser for arm
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release -f .goreleaser-arm.yml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}          
      -
        name: Upload assets
        uses: actions/upload-artifact@v2
        with:
          name: gclone
          path: dist/*
